# DATALOADER CONFIGURATIONS
TRAIN_BATCH_SIZE = 64
TEST_VAL_BATCH_SIZE = 32
TRAIN_SAMPLER = "random"
TEST_VAL_SAMPLER = "sequential"
TRAIN_DATALOADER_NUM_WORKERS = 20
TEST_VAL_DATALOADER_NUM_WORKERS = 10

# TRAINER CONFIGURATIONS
NUM_EPOCHS = 10

# OPTIMIZER CONFIGURATIONS
OPTIMIZER_NAME = "adam"
LEARNING_RATE = 0.0001
BETAS = (0.9, 0.999)
EPS = 1e-8
WEIGHT_DECAY = 0.0

# SCHEDULER CONFIGURATIONS
SCHEDULER_NAME = "step_lr"
STEP_SIZE = 30
GAMMA = 0.1
LAST_EPOCH=-1
MODE = "min"
FACTOR = 0.1
PATIENCE = 2
THRESHOLD = 1e-4
COOLDOWN = 0
EPS = 1e-8

# LOSS CONFIGURATION
LOSS_NAME = "cross_entropy"